# Generated by Django 6.0.5 on 2026-05-24 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='enrolled_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsection',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'is_teacher': True}, related_name='teaching_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='courses.course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='chapter_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chaptersection'),
        ),
        migrations.AddField(
            model_name='grade',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.classsection'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.module'),
        ),
    ]
