# Generated by Django 6.0.5 on 2026-05-24 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('open', 'Opened Activity'), ('complete', 'Completed Activity'), ('quiz_submit', 'Submitted Quiz'), ('time_heartbeat', 'Time Heartbeat')], max_length=20)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Tiempo invertido en esta sesión de actividad')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chapter_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chaptersection')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.classsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'section'], name='courses_act_student_968e7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SectionChapterControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_controls', to='courses.classsection')),
            ],
            options={
                'unique_together': {('section', 'chapter')},
            },
        ),
    ]
