# Generated by Django 6.0.5 on 2026-05-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtracurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('announcement', 'Anuncio'), ('zoom_link', 'Clase en Vivo'), ('extra_homework', 'Tarea Extra')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('url_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_activities', to='courses.classsection')),
            ],
        ),
    ]
