# Generated by Django 6.0.5 on 2026-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_extracurricularactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='max_students',
            field=models.IntegerField(default=0, help_text='0 significa sin límite de cupo'),
        ),
    ]
