# Generated by Django 6.0.5 on 2026-05-25 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_classsection_max_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCustomTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('assignment', 'Entrega de Tarea'), ('reading', 'Material de Lectura'), ('zoom', 'Clase en Vivo (Link)')], max_length=50)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('url_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tasks', to='courses.classsection')),
            ],
        ),
        migrations.CreateModel(
            name='SectionActivityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chaptersection')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_controls', to='courses.classsection')),
            ],
            options={
                'unique_together': {('section', 'activity')},
            },
        ),
    ]
