# Generated by Django 6.0.5 on 2026-05-25 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_sectioncustomtask_sectionactivitycontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracurricularactivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='extracurricularactivity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='extracurricularactivity',
            name='url_link',
        ),
        migrations.RemoveField(
            model_name='sectionactivitycontrol',
            name='is_unlocked',
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_activities', to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='section_type',
            field=models.CharField(choices=[('video', 'Video'), ('exercise', 'Ejercicio'), ('quiz', 'Quiz'), ('game', 'Juego'), ('practice', 'Práctica'), ('manual_task', 'Tarea Manual')], default='exercise', max_length=50),
        ),
        migrations.AddField(
            model_name='sectionactivitycontrol',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
