# Generated by Django 6.0.5 on 2026-05-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_chaptersection_section_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularactivity',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sectionactivitycontrol',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
