# Generated by Django 6.0.5 on 2026-05-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_extracurricularactivity_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularactivity',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
