# Generated by Django 6.0.5 on 2026-06-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_force_order_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='chapter_section',
            field=models.IntegerField(help_text='ID de ChapterSection (positivo) o ExtracurricularActivity (negativo)'),
        ),
    ]
