# Generated by Django 6.0.5 on 2026-06-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_activitylog_chapter_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptersection',
            name='section_type',
            field=models.CharField(choices=[('video', 'Video'), ('reading', 'Lectura'), ('exercise', 'Ejercicio'), ('exam', 'Examen'), ('quiz', 'Quiz'), ('game', 'Juego'), ('practice', 'Práctica'), ('manual_task', 'Tarea Manual')], default='video', max_length=20),
        ),
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='section_type',
            field=models.CharField(choices=[('video', 'Video'), ('reading', 'Lectura'), ('exercise', 'Ejercicio'), ('exam', 'Examen'), ('quiz', 'Quiz'), ('game', 'Juego'), ('practice', 'Práctica'), ('manual_task', 'Tarea Manual')], default='exercise', max_length=50),
        ),
    ]
